# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "Jonathan Loscalzo"
# theme = "hugo-coder"

baseurl = "http://www.example.com"
title = "Jonathan Loscalzo"

theme = "hugo-coder"

languagecode = "es"
defaultcontentlanguage = "es"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "jonathanloscalzo"

[params]
    author = "Jonathan Loscalzo"
    description = "Jonathan's personal website"
    keywords = "resume,blog,developer,personal"
    info = "Software Developer"
    avatarurl = "images/avatar-jloscalzo.jpeg"
    #gravatar = "john.doe@example.com"
    # footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []
    
    favicon_32 = "/images/icons8-laptop-16x16.png"
    favicon_16 = "/images/icons8-laptop-16x16.png"
# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"
    
# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
#     domain = "example.com"
#     # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/JonathanLoscalzo"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/jonathan-loscalzo-7a070279/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 3
    url = "https://medium.com/@jonathanloscalzo"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 4
    url = "https://twitter.com/jony_loscal"

# [[params.social]]
#     name = "RSS"
#     icon = "fas fa-rss"
#     weight = 6
#     url = "https://myhugosite.com/index.xml"
#     rel = "alternate"
#     type = "application/rss+xml"

[permalinks]
  posts = "/:year/:month/:slug/"

[languages]
    [languages.es]
        languagename = "Español"
        title = "Jonathan Loscalzo"

        [languages.es.menu]

            [[languages.es.menu.main]]
            name = "Curriculum"
            weight = 1
            url = "resume/"

            [[languages.es.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 5
            # url = "contact/"
    [languages.en]
        languagename = "English"

        [languages.en.params]
            author = "Jonathan Loscalzo"
            info = "Software Developer"
            description = "Sítio pessoal de João Ninguém"
            keywords = "resume,blog,developer,personal"
            # footercontent = "Coloque algum texto aqui."
        
        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Resume"
            weight = 1
            url = "resume/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 5
            # url = "contact/"


#    [languages.pt-br]
#        languagename = "Português"
#        title = "João Ninguém"
#
#        [languages.pt-br.params]
#            author = "João Ninguém"
#            info = "Full Stack DevOps e Mágico"
#            description = "Sítio pessoal de João Ninguém"
#            keywords = "blog,desenvolvedor,pessoal"
#            footercontent = "Coloque algum texto aqui."
#
#        [languages.pt-br.menu]
#
#            [[languages.pt-br.menu.main]]
#            name = "Sobre"
#            weight = 1
#            url = "about/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Projetos"
#            weight = 3
#            url = "projects/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Contato"
#            weight = 5
#            url = "contact/"
